changes for dev28

diff --git a/.github/workflows/pack-build.yml b/.github/workflows/pack-build.yml
--- a/.github/workflows/pack-build.yml
+++ b/.github/workflows/pack-build.yml
@@ -95,7 +95,7 @@ jobs:
             latestAutoScalingGroupName=$(aws autoscaling describe-auto-scaling-groups --query "sort_by(AutoScalingGroups, &CreatedTime)[-1].[AutoScalingGroupName]" --output "text")
             echo "latest AutoScalingGroupName:"
             echo $latestAutoScalingGroupName
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name  MyautoScalingGroup --launch-template LaunchTemplateId=$latestLaunchTemplateId,Version='$Latest'
+            aws autoscaling update-auto-scaling-group --auto-scaling-group-name MyautoScalingGroup --launch-template LaunchTemplateId=$latestLaunchTemplateId,Version='$Latest'
             latestVersion=$(aws ec2 describe-launch-templates --launch-template-id $latestLaunchTemplateId --query "sort_by(LaunchTemplates, &CreateTime)[-1].[LatestVersionNumber]" --output "text")
             echo "latestVersion:"
             echo $latestVersion
@@ -109,18 +109,20 @@ jobs:
 
       - name: Wait for Instance Refresh to Complete
         run: |
-          while true; do
-            refreshStatus=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $latestAutoScalingGroupName --query 'InstanceRefreshes[-1].Status' --output text)
-            echo $refreshStatus
-            if [ "$refreshStatus" == "Successful" ]; then
-              break
-            elif [ "$refreshStatus" == "Failed" ]; then
-              echo "Instance refresh failed."
-              exit 1
-            else
-              sleep 60
-            fi
-          done
+          latestAutoScalingGroupName=$(aws autoscaling describe-auto-scaling-groups --query "sort_by(AutoScalingGroups, &CreatedTime)[-1].[AutoScalingGroupName]" --output "text")
+          echo $latestAutoScalingGroupName
+           while true; do
+             refreshStatus=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $latestAutoScalingGroupName --query 'InstanceRefreshes[-1].Status' --output text)
+             echo $refreshStatus
+             if [ "$refreshStatus" == "Successful" ]; then
+               break
+             elif [ "$refreshStatus" == "Failed" ]; then
+               echo "Instance refresh failed."
+               exit 1
+             else
+               sleep 60
+             fi
+           done
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
