Assign 10 dev4

diff --git a/.github/workflows/pack-build.yml b/.github/workflows/pack-build.yml
--- a/.github/workflows/pack-build.yml
+++ b/.github/workflows/pack-build.yml
@@ -83,33 +83,31 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
           AWS_DEFAULT_REGION: us-west-2
 
-  aws_launch_template:
-    name: AWS Launch Template
-    needs: packagebuild
-    runs-on: ubuntu-latest
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
-          aws-region: us-west-2
-      - name: Launch Template
+      - name: Create new Launch Template version and refresh instances
         run: |
-          latestAmi=$(aws ec2 describe-images --filters "Name=owner-id,Values=286957373320" --query "sort_by(Images, &CreationDate)[-1].[ImageId]" --output "text")
-          echo "latest ami:"
-          echo $latestAmi
-          latestLaunchTemplateId=$(aws ec2 describe-launch-templates --query "sort_by(LaunchTemplates, &CreateTime)[-1].[LaunchTemplateId]" --output "text")
-          if [[ ${latestLaunchTemplateId} != 'None' ]]; then
-            echo "latest template id:"
-            echo $latestLaunchTemplateId
-            latestAutoScalingGroupName=$(aws autoscaling describe-auto-scaling-groups --query "sort_by(AutoScalingGroups, &CreatedTime)[-1].[AutoScalingGroupName]" --output "text")
-            echo "latest AutoScalingGroupName:"
-            echo $latestAutoScalingGroupName
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name  $latestAutoScalingGroupName --launch-template LaunchTemplateId=$latestLaunchTemplateId,Version='$Latest'
-            latestVersion=$(aws ec2 describe-launch-templates --launch-template-id $latestLaunchTemplateId --query "sort_by(LaunchTemplates, &CreateTime)[-1].[LatestVersionNumber]" --output "text")
-            echo "latestVersion:"
-            echo $latestVersion
-            aws ec2 create-launch-template-version --launch-template-id $latestLaunchTemplateId --version-description latest --source-version 1 --launch-template-data "ImageId=$latestAmi"
-            aws autoscaling start-instance-refresh --auto-scaling-group-name $latestAutoScalingGroupName --preferences "InstanceWarmup=200"
-          fi
+          latest_ami_id=$(aws ec2 describe-images --owners 097171053993 --query 'Images | [-1].ImageId' --output text)
+          aws ec2 create-launch-template-version --launch-template-name YourLaunchTemplateName --version-description "New version with latest AMI" --source-version "$latest_ami_id"
+
+
+          # Issue an instance refresh to the autoscaling group
+          aws autoscaling start-instance-refresh --auto-scaling-group-name MyautoScalingGroup
+
+      - name: Wait for Instance Refresh to Complete
+
+        run: |
+          while true; do
+            refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name YourAutoScalingGroupName --query 'InstanceRefreshes[-1].Status' --output text)
+            if [ "$refresh_status" == "Successful" ]; then
+              break
+            elif [ "$refresh_status" == "Failed" ]; then
+              echo "Instance refresh failed."
+              exit 1
+            else
+              sleep 60
+            fi
+          done
+
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
+          AWS_DEFAULT_REGION: us-west-2
