Changes for assign 10 dev20

diff --git a/.github/workflows/pack-build.yml b/.github/workflows/pack-build.yml
--- a/.github/workflows/pack-build.yml
+++ b/.github/workflows/pack-build.yml
@@ -100,33 +100,21 @@ jobs:
             echo "latestVersion:"
             echo $latestVersion
             aws ec2 create-launch-template-version --launch-template-id $latestLaunchTemplateId --version-description latest --source-version 1 --launch-template-data "ImageId=$latestAmi"
-            aws autoscaling start-instance-refresh --auto-scaling-group-name MyautoScalingGroup --preferences "InstanceWarmup=200"
-          fi
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
-          AWS_DEFAULT_REGION: us-west-2
-
-      - name: Wait for Instance Refresh to Complete
-        run: |
-          timeout=0
-          max_timeout=600  
-          while [ $timeout -lt $max_timeout ]; do
-          refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name MyautoScalingGroup --query 'InstanceRefreshes[-1].Status' --output text)
-          echo "Refresh status: $refresh_status"
-          if [ "$refresh_status" == "Successful" ]; then
-            break
-          elif [ "$refresh_status" == "Failed" ]; then
-            echo "Instance refresh failed."
-            exit 1
-          else
-            sleep 60
-            timeout=$((timeout + 60))
-          fi
-          done
-          if [ $timeout -ge $max_timeout ]; then
-            echo "Timeout exceeded. Instance refresh taking longer than expected."
-            exit 1
+            refreshId=$(aws autoscaling start-instance-refresh --auto-scaling-group-name MyautoScalingGroup --preferences "InstanceWarmup=200" --query 'InstanceRefreshId' --output 'text')
+            echo "Instance refresh started. Waiting for completion..."
+            while true; do
+              refreshStatus=$(aws autoscaling describe-instance-refreshes --instance-refresh-ids $refreshId --query 'InstanceRefreshes[0].[Status]' --output 'text')
+              echo "Refresh status: $refresh_status"
+              if [ "$refreshStatus" == "Successful" ]; then
+                echo "Instance refresh completed successfully."
+                break
+              elif [ "$refreshStatus" == "Failed" ]; then
+                echo "Instance refresh failed. Check AWS Console for details."
+                exit 1
+              fi
+              echo "Instance refresh status: $refreshStatus. Waiting..."
+              sleep 60  # Adjust the sleep interval as needed
+            done
           fi
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
